Initial setup for Phase 2: Added return tokens to lexer file
Howie315/CS152-Project- pull request #18
Opened 2023-04-21 06:26 UTC by GodfreyL3

2023-04-21 07:10 UTC, CoolGuyRy approved these changes

2023-04-21 07:13 UTC, CoolGuyRy requested changes
A couple things I commented need to be addressed. But other than that lgtm!

2023-04-21 07:13 UTC, CoolGuyRy commented on src/lexer.lex
> +{INTEGER}       	{ return INTEGER }
fprintf(yyout, "INTEGER \n"); lineCharacterCount += yyleng; should be here. If not our lineCharacterCount will be off whenever ints are declared.

2023-04-21 07:13 UTC, CoolGuyRy commented on src/lexer.lex
> +{DOUBLE}    		{ return DOUBLE }
same thing here

2023-04-21 07:13 UTC, CoolGuyRy commented on src/lexer.lex
> +.       		{ printf("Error: Unrecognized symbol \"%s\" on line %d, col %d\n", yytext, lineCount + 1, lineCharacterCount + 1); lineCharacterCount += yyleng; return .;}
Is this the right way to return errors?

2023-04-21 07:13 UTC, CoolGuyRy commented on src/lexer.lex
> +{BAD_IDENTIFIER}	{ printf("Error: Invalid identifier %s on line %d, col %d\n", yytext, lineCount + 1, lineCharacterCount + 1); lineCharacterCount += yyleng; return BAD_IDENTIFIER; }
Is this the right way to return errors?

2023-04-28 05:09 UTC, Howie315 approved these changes

2023-04-28 05:16 UTC, merged